### PR TITLE
add responsive design

### PR DESCRIPTION
**Pull request by tsongtheng**
## issue #31 
taskboard

### CODE REVIEW

**Review by killerkc12 — CHANGES_REQUESTED** [review]
Need some improvements
1. For the Desktops and Tablets view, a vertical scrollbar should not come, only a horizontal scrollbar is allowed if the tasklist has more than the screen width.
2. For Mobile view, Only a Vertical scrollbar is allowed, horizontal scrollbar is not allowed.
3. In Mobile view, Navbar should contain Menu Icon, Search bar and Profile Icon.

**Review by tsongtheng — COMMENTED** [review]
Update responsive design

https://github.com/killerkc12/Taskboard/assets/69814398/58e975bb-e6db-419b-a8f2-6a9f5f179ae8

**Comment by killerkc12** [comment]
@tsongtheng Perfect!

**Review by killerkc12 — APPROVED** [review]
Thank you for taking the time to contribute to this project. Your changes are a valuable addition.

**Pull request merged**
