### PR TITLE
TaskList height bug-fix

### PR DESCRIPTION
**Pull request by tsongtheng**
### Fixed the height of TaskList.

taskbar-screenshot

### CODE REVIEW

**Comment by killerkc12** [comment]
The tasklist is going over of screen height when I add extra tasks. Please handle this
image

**Comment by tsongtheng** [comment]
@killerkc12 , it looks fine in my PC. May be it's because I am working on LINUX environment. Let me check it in Windows PC and give you a feedback.

Also, please check the ***font-size*** of your browser, if it is **100%** or not.

**Comment by killerkc12** [comment]
@tsongtheng Yes, the text size of my PC is 125%. But we say the user will have 100% text size. So please make the changes that will handle even text size is different.

**Comment by tsongtheng** [comment]
Hey @killerkc12 , we have to change the `root` ***font-size*** into percentage to have that feature. I can do that. But I will convert the `pixel` into  `rem` of all the components and files, if that's ok?. 

If this PR is merge, all the later **updates**  will have to use `rem` in place of  `px` to avoid the breakdown of UI component.

**Comment by killerkc12** [comment]
This PR has not been merged yet. Let me know if you're abled to do this changes in same PR.
Otherwise I'll merge this PR then you can create new PR for those changes.

**Comment by tsongtheng** [comment]
@killerkc12 , I will create a new PR.

**Review by killerkc12 — APPROVED** [review]
The changes look cool
@tsongtheng Please create a new PR.

**Comment by killerkc12** [comment]
@tsongtheng Please link the PR with related issue

**Comment by tsongtheng** [comment]
OK.

**Pull request merged**
